'use strict';
(() => {
 const defaults={threshold_ratio:.3,refractory_ms:250,match_ms:100};
 const method={name:'slope-energy/1',smooth_samples:11,derivative_half_span:5,energy_samples:81,baseline_samples:201,refine_radius_samples:80,score_quantum_mv2:1e-12,input_quantum_mv:1e-6,localization_quantum_mv:1e-6,threshold_source:'maximum recorded-input score in [1000,7000), shared by both branches',matching:'maximum-cardinality, minimum-total-absolute-delay-adjusted-shift; ordered pairs'};
 function validate(c){if(!c||Object.keys(c).sort().join()!==Object.keys(defaults).sort().join())throw Error('Unexpected detector settings.');for(const [k,lo,hi] of [['threshold_ratio',.1,1],['refractory_ms',200,500],['match_ms',20,150]])if(typeof c[k]!=='number'||!Number.isFinite(c[k])||c[k]<lo||c[k]>hi||(k!=='threshold_ratio'&&!Number.isInteger(c[k])))throw Error('Invalid '+k);}
 function sums(x,w){const half=(w-1)/2;let sum=0;for(let j=0;j<=half;j++)sum+=x[j];const y=[];for(let i=0;i<x.length;i++){y.push(sum);if(i-half>=0)sum-=x[i-half];if(i+half+1<x.length)sum+=x[i+half+1];}return y;}
 function features(x){
  if(!Array.isArray(x)||x.length!==8000||x.some(v=>typeof v!=='number'||!Number.isFinite(v)||Math.abs(v)>32))throw Error('Detector requires 8,000 finite samples within ±32 mV.');
  const fixed=x.map(v=>Math.floor(v*1e6+.5)),smooth=sums(fixed,11),baseline=sums(fixed,201);
  const squares=x.map((_,i)=>{const v=BigInt(i>=5&&i<7995?smooth[i+5]-smooth[i-5]:0);return v*v;});
  let sum=0n;for(let i=0;i<=40;i++)sum+=squares[i];const score=[];
  for(let i=0;i<8000;i++){score.push(Number((2n*sum+9801n)/19602n));if(i>=40)sum-=squares[i-40];if(i+41<8000)sum+=squares[i+41];}
  return {score,amplitude:fixed.map((v,i)=>Math.floor((2*Math.abs(v*201-baseline[i])+201)/402))};
 }
 function candidates(score,amplitude,threshold,refractory){if(threshold<=0)return [];const peaks=[];for(let i=1;i<score.length-1;i++){if(score[i]>score[i-1]){let end=i;while(end+1<score.length&&score[end+1]===score[i])end++;if(end<score.length-1&&score[end]>score[end+1]&&score[i]>=threshold)peaks.push(Math.floor((i+end)/2));i=end;}}peaks.sort((a,b)=>score[b]-score[a]||a-b);const accepted=[];for(const p of peaks){if(p<920||p>=7080)continue;let top=-Infinity,first=0,last=0;for(let i=Math.max(0,p-80);i<Math.min(8000,p+81);i++){if(amplitude[i]>top){top=amplitude[i];first=i;last=i;}else if(amplitude[i]===top)last=i;}const q=Math.floor((first+last)/2);if(q>=1000&&q<7000&&accepted.every(v=>Math.abs(v-q)>=refractory))accepted.push(q);}return accepted.sort((a,b)=>a-b);}
 function pair(r,o,delay,tolerance){const dp=Array.from({length:r.length+1},()=>Array.from({length:o.length+1},()=>({count:0,cost:0,pairs:[]})));for(let i=r.length-1;i>=0;i--)for(let j=o.length-1;j>=0;j--){const options=[dp[i+1][j],dp[i][j+1]],delta=o[j]-r[i]-delay;if(Math.abs(delta)<=tolerance){const next=dp[i+1][j+1];options.unshift({count:next.count+1,cost:next.cost+Math.abs(delta),pairs:[[r[i],o[j]],...next.pairs]});}let best=options[0];for(const v of options.slice(1))if(v.count>best.count||v.count===best.count&&v.cost<best.cost)best=v;dp[i][j]=best;}return dp[0][0].pairs.map(([a,b])=>({recorded_sample:a,output_sample:b,shift_ms:b-a,adjusted_shift_ms:b-a-delay}));}
 function median(x){if(!x.length)return null;const s=[...x].sort((a,b)=>a-b),n=s.length;return n%2?s[(n-1)/2]:(s[n/2-1]+s[n/2])/2;}
 function rate(x){return x.length<2?null:60000/median(x.slice(1).map((v,i)=>v-x[i]));}
 function analyze(arrays,c,delay){validate(c);const r=features(arrays.recorded),o=features(arrays.output),threshold=Math.max(...r.score.slice(1000,7000))*c.threshold_ratio,rp=candidates(r.score,r.amplitude,threshold,c.refractory_ms),op=candidates(o.score,o.amplitude,threshold,c.refractory_ms),matches=pair(rp,op,delay,c.match_ms),rr=rate(rp),ro=rate(op);return {method:{...method},analysis_samples:[1000,7000],threshold_score_units:threshold,recorded_peaks:rp,output_peaks:op,matches,recorded_only:rp.filter(p=>!matches.some(m=>m.recorded_sample===p)),output_only:op.filter(p=>!matches.some(m=>m.output_sample===p)),recorded_rate_bpm:rr,output_rate_bpm:ro,rate_change_bpm:rr!==null&&ro!==null?ro-rr:null,median_shift_ms:median(matches.map(m=>m.shift_ms)),median_adjusted_shift_ms:median(matches.map(m=>m.adjusted_shift_ms)),recorded_score_units:r.score,output_score_units:o.score};}
 function evaluate(analysis,c){return {schema:'ecg-atlas-beats/1',analysis,detector:{...c},detection:analyze(analysis.arrays,c,analysis.metrics.filter_delay_ms)};}
 globalThis.ECGBeats={defaults,validate,features,candidates,pair,analyze,evaluate};
})();
